// This file is @generated by prost-build.
/// FUNCTION: sign_tx(SignParam{input: AtomTxInput}): AtomTxOutput
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AtomTxInput {
    /// hex string
    #[prost(string, tag = "1")]
    pub raw_data: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AtomTxOutput {
    /// hex string
    #[prost(string, tag = "1")]
    pub signature: ::prost::alloc::string::String,
}
