[package]

name = "secp256k1"
version = "0.15.3"
authors = [ "Dawid Ciężarkiewicz <dpc@ucore.info>",
            "Andrew Poelstra <apoelstra@wpsoftware.net>" ]
license = "CC0-1.0"
homepage = "https://github.com/rust-bitcoin/rust-secp256k1/"
repository = "https://github.com/rust-bitcoin/rust-secp256k1/"
documentation = "https://docs.rs/secp256k1/"
description = "Rust bindings for Pieter Wuille's `libsecp256k1` library. Implements ECDSA for the SECG elliptic curve group secp256k1 and related utilities."
keywords = [ "crypto", "ECDSA", "secp256k1", "libsecp256k1", "bitcoin" ]
readme = "README.md"
build = "build.rs"
links = "secp256k1"

# Should make docs.rs show all functions, even those behind non-default features
[package.metadata.docs.rs]
features = [ "rand", "serde", "recovery", "endomorphism" ]

[build-dependencies]
cc = ">= 1.0.28"

[lib]
name = "secp256k1"
path = "src/lib.rs"
crate-type = ["staticlib", "cdylib"]

[features]
unstable = []
default = ["std"]
fuzztarget = []
std = ["rand/std"]
recovery = []
endomorphism = []
lowmemory = []

[dev-dependencies]
rand = "=0.8.5"
rand_core = "0.6.4"
serde_test = "1.0"

[dependencies.rand]
version = "0.6"
optional = true
default-features = false

[dependencies.serde]
version = "1.0"
optional = true
default-features = false

[workspace]