// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Utxo {
    #[prost(string, tag = "1")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub vout: u32,
    #[prost(uint64, tag = "3")]
    pub amount: u64,
    #[prost(string, tag = "4")]
    pub address: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub script_pub_key: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub derived_path: ::prost::alloc::string::String,
    #[prost(int64, tag = "7")]
    pub sequence: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BtcTxExtra {
    #[prost(string, tag = "1")]
    pub op_return: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub property_id: i32,
    #[prost(string, tag = "3")]
    pub fee_mode: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BtcTxInput {
    #[prost(string, tag = "1")]
    pub to: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub amount: u64,
    #[prost(uint64, tag = "3")]
    pub fee: u64,
    #[prost(uint32, optional, tag = "4")]
    pub change_address_index: ::core::option::Option<u32>,
    #[prost(message, repeated, tag = "5")]
    pub unspents: ::prost::alloc::vec::Vec<Utxo>,
    #[prost(string, tag = "6")]
    pub seg_wit: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub protocol: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "8")]
    pub extra: ::core::option::Option<BtcTxExtra>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BtcTxOutput {
    #[prost(string, tag = "1")]
    pub signature: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub wtx_hash: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PsbtInput {
    #[prost(string, tag = "1")]
    pub psbt: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub auto_finalize: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PsbtOutput {
    #[prost(string, tag = "1")]
    pub psbt: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BtcMessageInput {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
    #[prost(enumeration = "BtcSignatureType", tag = "2")]
    pub signature_type: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BtcMessageOutput {
    #[prost(string, tag = "1")]
    pub signature: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BtcSignatureType {
    Standard = 0,
    Bip137 = 1,
    Bip322 = 2,
}
impl BtcSignatureType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Standard => "STANDARD",
            Self::Bip137 => "BIP137",
            Self::Bip322 => "BIP322",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "STANDARD" => Some(Self::Standard),
            "BIP137" => Some(Self::Bip137),
            "BIP322" => Some(Self::Bip322),
            _ => None,
        }
    }
}
