[package]
name = "coin-eos"
version = "0.1.0"
authors = ["joe <xielamenla@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ikc-common = {path = "../../ikc-common"}
ikc-device = {path = "../../ikc-device"}
ikc-transport = {path = "../../ikc-transport"}
bitcoin_hashes = "=0.11.0"
hex = "=0.4.3"
bitcoin = "=0.29.2"
anyhow = "=1.0.79"
bytes = "=1.4.0"
prost = "=0.11.2"
prost-types = "=0.11.2"