[package]
name = "tcx-crypto"
version = "0.1.0"
authors = ["Neal Xu <imxuneal@gmail.com>"]
edition = "2021"

[dependencies]
tcx-constants = {path="../tcx-constants"}
tcx-common = {path="../tcx-common"}

serde_json = "=1.0.89"
serde = { version = "=1.0.165", features = ["derive"] }
rand = "=0.8.5"
tiny-keccak = { version = "=2.0.2", features = ["keccak"] }
scrypt = { version = "=0.10.0", default-features = false }
sha2 = "=0.10.6"
digest = "=0.10.6"
hmac = "=0.12.1"
aes = "=0.8.3"
ctr = "=0.9.2"
cbc = "=0.1.2"
pbkdf2 = "=0.11.0"
bitcoin_hashes = "=0.11.0"
crypto-mac = "=0.11.1"
anyhow = { version = "=1.0.79", features = [] }
secp256k1 = {version ="=0.24.3", features = ["rand", "recovery"] }
hex = "=0.4.3"
lazy_static = "=1.4.0"
regex = "=1.9.3"

parking_lot = "=0.12.1"
thiserror = "=1.0.56"

[features]
default = []
cache_dk = []
