[package]
name = "coin-ethereum"
version = "0.1.0"
authors = ["IMLXM <liuxm1986@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ikc-common = {path = "../../ikc-common"}
ikc-device = {path = "../../ikc-device"}
ikc-transport = {path = "../../ikc-transport"}
rlp = "=0.5.2"
secp256k1 = {version ="=0.24.3", features = ["rand", "recovery"] }
ethereum-types = "=0.14.0"
keccak-hash = "=0.10.0"
lazy_static = "=1.4.0"
rustc-hex = "=2.1.0"
serde_json = "=1.0.89"
serde = { version = "=1.0.165", features = ["derive"] }
serde_derive = "=1.0.165"
jsonrpc-core = "=18.0.0"
bitcoin = "=0.29.2"
bitcoin_hashes = "=0.11.0"
hex = "=0.4.3"
regex = "=1.9.3"
tiny-keccak = { version = "=2.0.2", features = ["keccak"] }
anyhow = "=1.0.79"
num-bigint = "=0.4.6"
num-traits = "=0.2.19"
num-integer = "=0.1.46"
bytes = "=1.4.0"
prost = "=0.11.2"
prost-types = "=0.11.2"
base64 = "=0.13.1"