[package]
name = "wallet-core-common"
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"

[features]
default = []
aes = ["dep:aes", "dep:cbc", "dep:ctr"]
bip32 = ["dep:bitcoin"]
btc = ["dep:bitcoin"]
ckb-address = ["dep:bech32", "dep:bitcoin", "dep:blake2b-rs", "dep:blake2b_simd"]
cosmos = ["dep:bech32", "dep:bitcoin"]
curve = ["dep:serde"]
eth = ["dep:keccak-hash"]
filecoin = ["dep:base32", "dep:blake2b-rs", "dep:blake2b_simd"]
hash = ["dep:bitcoin", "dep:keccak-hash"]
path = ["dep:bitcoin"]
tezos = ["dep:bitcoin", "dep:blake2b_simd"]
tron = ["dep:bitcoin", "dep:keccak-hash"]
utility = [
    "aes",
    "bip32",
    "hash",
    "dep:base64",
    "dep:num-bigint",
    "dep:num-integer",
    "dep:num-traits",
    "dep:secp256k1",
]

[dependencies]
aes = { version = "=0.9.1", optional = true }
anyhow = "=1.0.103"
base32 = { version = "=0.5.1", optional = true }
bech32 = { version = "=0.11.1", optional = true }
bitcoin = { version = "=0.32.9", optional = true }
blake2b_simd = { version = "=1.0.4", optional = true }
cbc = { version = "=0.2.1", optional = true }
ctr = { version = "=0.10.1", optional = true }
hex = "=0.4.3"
keccak-hash = { version = "=0.12.0", optional = true }
num-bigint = { version = "=0.4.6", optional = true }
num-integer = { version = "=0.1.46", optional = true }
num-traits = { version = "=0.2.19", optional = true }
base64 = { version = "=0.22.1", optional = true }
secp256k1 = { version = "=0.31.1", features = ["rand", "recovery"], optional = true }
serde = { version = "=1.0.228", features = ["derive"], optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
blake2b-rs = { version = "=0.2.0", optional = true }
