[package]
name = "tcx-wallet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tcx-primitive = { path = "../tcx-primitive" }

failure = "0.1.8"
prost = "0.11.2"
prost-types = "0.11.2"