[package]
name = "tcx-common"
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "=1.0.102", features = [] }
wallet-core-common = { path = "../../common/wallet-core-common", features = ["hash"] }
regex = "=1.12.3"
ctr = "=0.10.1"
aes = "=0.9.1"
secp256k1 = "=0.31.1"
tiny-bip39 = "=2.0.0"
rand = "=0.10.1"
ethereum-types = "=0.16.0"
thiserror = "=2.0.18"
