[package]
name = "coin-filecoin"
version = "0.1.0"
authors = ["wyoyw <wyoyw@126.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ikc-common = {path = "../../ikc-common"}
ikc-device = {path = "../../ikc-device"}
ikc-transport = {path = "../../ikc-transport"}


bitcoin_hashes = "=0.11.0"
hex = "=0.4.3"
secp256k1 = {version ="=0.24.3", features = ["rand", "recovery"] }
bech32 = "=0.9.1"
num-bigint = "=0.4.6"
num = "0.4.3"
num-traits = "=0.2.19"
num-integer = "=0.1.46"
base64 = "=0.13.1"
anyhow = "=1.0.79"
bytes = "=1.4.0"
prost = "=0.11.2"
prost-types = "=0.11.2"
linked-hash-map = { version = "=0.5.6", features = ["serde_impl"] }

base32 = "=0.4.0"
blake2b-rs = "=0.2.0"
serde = { version = "=1.0.165", features = ["derive"] }
serde_json = "=1.0.89"

multihash-codetable = { version = "=0.1.3", features = ["blake2b"] }
cid = "=0.11.1"
fvm_shared = "=4.3.1"
fvm_ipld_encoding = "0.4.0"
serde_tuple = "0.5.0"
strum_macros = "0.26.3"
strum = { version = "0.26.3", features = ["derive"] }
bitcoin = "=0.29.2"
num-derive = "0.4.2"

