[package]
name = "coin-filecoin"
version = "0.1.0"
authors = ["wyoyw <wyoyw@126.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ikc-common = {path = "../../ikc-common"}
ikc-device = {path = "../../ikc-device"}
ikc-transport = {path = "../../ikc-transport"}


bitcoin_hashes = "=0.11.0"
hex = "=0.4.3"
secp256k1 = {version ="=0.24.3", features = ["rand", "recovery"] }
bech32 = "=0.9.1"
num-bigint = "=0.4.3"
num-traits = "=0.2.15"
num-integer = "=0.1.45"
base64 = "=0.13.1"
anyhow = "=1.0.79"
bytes = "=1.4.0"
prost = "=0.11.2"
prost-types = "=0.11.2"
linked-hash-map = { version = "=0.5.6", features = ["serde_impl"] }

base32 = "=0.4.0"
blake2b-rs = "=0.2.0"
serde = { version = "=1.0.147", features = ["derive"] }
serde_json = "=1.0.89"

forest_vm = "=0.3.2"
forest_message = "=0.7.2"
forest_address = "=0.3.2"
forest_encoding = "=0.2.2"
forest_cid = "=0.3.0"
forest_crypto = "=0.5.3"
num_bigint_chainsafe = { package = "forest_bigint", version = "=0.1.4"}
bitcoin = "=0.29.2"

