[parse.expand]
# A list of crate names that should be run through `cargo expand` before
# parsing to expand any macros
crates = ["tcx-lib"]
# # If enabled,  use the `--all-features` option when expanding. Ignored when
# # `features` is set. Disabled by default, except when using the
# # `expand = ["euclid"]` shorthand for backwards-compatibility.
# all_features = false
# # When `all_features` is disabled and this is also disabled, use the
# # `--no-default-features` option when expanding. Enabled by default.
# default_features = true
# # A list of feature names that should be used when running `cargo expand`. This
# # combines with `default_features` like in `Cargo.toml`. Note that the features
# # listed here are features for the current crate being built, *not* the crates
# # being expanded. The crate's `Cargo.toml` must take care of enabling the
# # appropriate features in its dependencies
# features = ["cbindgen"]
