[package]
name = "tcx-chain"
version = "0.1.0"
authors = ["Neal Xu <imxuneal@gmail.com>"]
edition = "2018"

[dependencies]
tcx-crypto = { path = "../tcx-crypto" }
tcx-primitive = { path = "../tcx-primitive" }
tcx-constants = { path = "../tcx-constants" }

bitcoin = "0.29.2"
byteorder = "1.4.3"
secp256k1 = {version ="0.24.1", features = ["rand", "recovery"] }
tiny-bip39 = "0.7.3"
bitcoin_hashes = "0.11.0"
uuid = { version = "1.2.2", features = ["serde", "v4"] }
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.88"
failure = "0.1.8"
regex = "1.7.0"
hex = "0.4.3"

prost = "0.11.2"
bytes = "1.3.0"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["precommit-hook", "run-cargo-fmt"]


[features]
default = []
cache_dk = []