language: rust
cache: 
  directories:
  - cargo_web

rust:
  - stable
  - beta
  - nightly
  - 1.22.0
os:
 - linux
 - windows

addons:
  chrome: stable

matrix:
  exclude:
  - rust: 1.22.0
    os: windows

script:
  - cargo build --verbose --no-default-features
  - cargo build --verbose --no-default-features --features="serde"
  - cargo build --verbose --no-default-features --features="lowmemory"
  - cargo build --verbose --no-default-features --features="rand"
  - cargo build --verbose --no-default-features --features="rand serde recovery endomorphism"
  - cargo build --verbose --no-default-features --features="fuzztarget recovery"
  - cargo build --verbose --features=fuzztarget
  - cargo build --verbose --features=rand
  - cargo test --verbose --features=rand
  - cargo test --verbose --features="rand serde"
  - cargo test --verbose --features="rand serde recovery endomorphism"
  - cargo build --verbose
  - cargo test --verbose
  - cargo build --verbose --release
  - cargo test --verbose --release
  - if [ ${TRAVIS_RUST_VERSION} == "stable" ]; then cargo doc --verbose --features="rand,serde,recovery,endomorphism"; fi
  - if [ ${TRAVIS_RUST_VERSION} == "nightly" ]; then cargo test --verbose --benches --features=unstable; fi
  - if [ ${TRAVIS_RUST_VERSION} == "stable" -a "$TRAVIS_OS_NAME" = "linux" ]; then 
    CARGO_TARGET_DIR=cargo_web cargo install --verbose --force cargo-web && 
    cargo web build --verbose --target=asmjs-unknown-emscripten && 
    cargo web test --verbose --target=asmjs-unknown-emscripten; 
    fi
